// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3I0kEkMHoUyFvHZ8NebnLX_EhuHYxyF0',
    appId: '1:600359875882:web:ce99dd15b5317e3750da53',
    messagingSenderId: '600359875882',
    projectId: 'ielts-ai-study-assistant',
    authDomain: 'ielts-ai-study-assistant.firebaseapp.com',
    storageBucket: 'ielts-ai-study-assistant.firebasestorage.app',
    measurementId: 'G-YPQ63LGMLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTpDEPASh9LqEn5HiD4XK4ncRY0qcumMQ',
    appId: '1:600359875882:android:b107819122a8c4c250da53',
    messagingSenderId: '600359875882',
    projectId: 'ielts-ai-study-assistant',
    storageBucket: 'ielts-ai-study-assistant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1xw5Z9g528TqUVUrrqHVNkRF0EtvtzNo',
    appId: '1:600359875882:ios:da40b2c42d789b7a50da53',
    messagingSenderId: '600359875882',
    projectId: 'ielts-ai-study-assistant',
    storageBucket: 'ielts-ai-study-assistant.firebasestorage.app',
    iosBundleId: 'com.example.fyproject',
  );
}
